### ISSUE TITLE
Fill in Health Tracker with VT SOs

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#102]
**Who is the user?**
Tammy & Dion (pilot SO partners in VT)

**What will this help them do?**
capture an initial visualization of the current health status of VT's MES

**What steps are needed to make it a reality?**
- [x] create Mural, populated with 1st draft of circles from [VT MDBT 🔒](https://drive.google.com/drive/folders/1dYIfSr0dV3vGXTWIVXJ3rtioVhdNYPof)
- [x] prep agenda for session w/ T&D
- [ ] work with T&D during session to get tracker updated based on their knowledge of VT's MES
- [ ] translate any next actions into Zenhub issues

**Comment by alexpandel** [comment]
update: T&D had to reschedule our meeting today to later this week (new time TBD), but the Mural we'll use is [here](https://app.mural.co/t/gsa6/m/gsa6/1597678271076/57cf64dccd5d76fabfec40718bd8af4a40149ca4). The MDBTs we received didn't include the tab breakdown by system/project, but hopefully we'll get those ahead of time and can update the Mural to be a bit more pre-populated than it is now.

**Comment by amyashida** [comment]
Update: blocked by finding time with T&D
