### ISSUE TITLE
Decide on form tool for Health Tracker

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#146]
**Brief description of the task** 

We decided to use a form to collect the rubric data. We need to make sure the tool is cleared for pilot use by CMS or find an alternative tool. 

**What steps are needed to make it a reality?**
- [x] 18F to collect ATO info from GSA
- [x] 18F to add ATO + alternate tool info to this issue
- [x] Nick to navigate any needed sign offs on CMS side

**Comment by amyashida** [comment]
@NAretakis what kind of documentation do you need on our end? This is the high level info of the Airtable ATO on our side. 

![image.png](https://images.zenhubusercontent.com/563a2ca4638e718c995e4667/c0ffda32-fc6b-41cc-bcc2-448441babf67)

Guidance on our end is that it is fine to use for prototype data but have been advised that we will want to check with your side before adding non-prototype data. We also cannot store PII in it, but none of the Health Rubric questions would constitute that.

Alternative tools to check out on your side (also you may have options available on your side I don't know about): 
- Google forms 
- Google appsheet
- Smartsheet

**Comment by alexpandel** [comment]
@NAretakis let us know if this 👆 is what you need and if there's anything else needed here before we close this issue!

**Comment by alexpandel** [comment]
@NAretakis are we decided on this one? is this closable for now?

**Comment by amyashida** [comment]
@NAretakis  can we close this for now?

**Comment by NAretakis** [comment]
Yup, closing this out.
