### ISSUE TITLE
Prep presentations for Heath Tracker roll out

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#149]
**Brief description of the task** 

We will be introducing the Health Tracker at the all teams meeting and want to involve pilot SOs 

**What steps are needed to make it a reality?**
- [x] draft presentation for All Teams (9/29)
- [x] sync w 18F & pilot SOs on All Hands talking points (at 9/26 cowork)
- [x] draft presentation outline/talking points for Office Hours session (10/6)
- [x] Sync w 18F & pilot SOs on what we want to cover and who's doing what for Office Hours (at 10/1 cowork)
- [x] create presentation

**Comment by amyashida** [comment]
@NAretakis I reassigned this to you since you're leading the discussion. 

The pilot SOs are joining our standing meeting tomorrow to discuss All Teams + Office Hours. It would be great to have talking points ready to get their feedback on. 

Here are a few ideas we had, feel free to work with them in the way that works best for you: 

**Top messages:** 

1. Reiterating the big picture of where DSG is headed overall
2. How the tracker is connected to that, and why the core concepts are important to DSG 
3. Here’s where you can find more info about this, and what to expect from here

**Additional talking point ideas:**
What are the core indicators? Where did they come from? 

What is Airtable? 

Shout outs to pilot SOs for their contributions

Spell out the support available & plan from here: 
- follow-ons with more info in Office Hours & individual Team meetings
- Maybe: introduce “SME cohort” concept? Or hint at training that will be available?
- Not expected to use this with your states yet, but will be coming soon, so wanted to get it on your radar so you had time to get familiar, ask questions, and build confidence in the subject matter

**Comment by NAretakis** [comment]
Presented at all-teams.
