### ISSUE TITLE
Identify initial Heath Tracker SO cohort 

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#152]
**Brief description of the task** 

Work with team leads to identify the first cohort to start creating support for and introducing the Health Tracker so we can start building up SMEs. 

**What steps are needed to make it a reality?**
- [ ] Meet with Team Leads to give heads up and start building buy in 
- [ ] Work with Team Leads to identify individuals
- [ ] Draft plan for engaging cohort

**Comment by alexpandel** [comment]
this is done I believe, yay!
