### ISSUE TITLE
Prep Health Tracker one-pager for release before All Teams 

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#153]
**Brief description of the task** 

The Health Tracker wiki content is going to be released to supplement Nick's presentation at All Teams on 9/29. We need to make sure it is ready to go! 

The wiki content will help SOs find the materials and info about the Health Tracker after the presentation.  

**What steps are needed to make it a reality?**
- [x] Align on what is going to be published
- [x] Make any needed edits
- [x] Publish before All Teams presentation 9/29
- [x] share link in Teams immediately following All Teams preso

**Comment by alexpandel** [comment]
heads up @NAretakis @LizLeBreton, the correct draft for this is the one Amy shared yesterday in our Teams chat, filename "Health Tracker Wiki Draft.docx"!
