### ISSUE TITLE
Add details about the Health Tracker workflow to SO wiki

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#155]
**Brief description of the task** 

The wiki will provide SOs with background on the tool, an overview of how to use it, and suggestions for using the Tracker with their states. The goal is to provide SOs with the resources needed to feel confident using the Tracker. 

18F will draft the pages and then collect feedback and input from pilot SOs as well as the CMS workstream leads. 

**What steps are needed to make it a reality?**
- [x] @alexpandel draft overview of SO workflow
- [x] share w/ CMS for feedback
- [x] capture feedback (in 10/1 meeting)
- [x] incorporate feedback & decide on next steps
- [x] CMS publish on wiki (and link out from Health Tracker one-pager)

**Comment by alexpandel** [comment]
reassigning this one to you @NAretakis & @LizLeBreton, since we're now looking for your (and C & D's) feedback on this. If/when this falls back onto our plate, feel free to reassign back to one of us!

**Comment by NAretakis** [comment]
Published on our wiki!
