### ISSUE TITLE
Review health tracker entries for insights

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#167]
**Brief description of the task** 

Give leadership insights into what we have collected so far via the Health Tracker

Target deadline: 10/16

**What steps are needed to make it a reality?**
- [ ] 18F to review entries
- [ ] 18F to document patterns/insights
- [ ] 18F to share above w/ CMS

**Comment by nickarrow** [comment]
Moving to Icebox until we start dash-boarding work.
