### ISSUE TITLE
transfer repo content over to DSG repo

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#17]
**What steps are needed to make this a reality?**
- [x] copy over any remaining open issues from old repo; for each one, make sure:
  - [x] new issue is well scoped and properly tagged
  - [x] old issue is closed & linked to new one
- [x] make sure all remaining issues in old repo are closed (with a comment explaining why)
- [x] make sure all content in wiki is framed properly for shared repo

**Comment by NAretakis** [comment]
Copied issues! But I think the board got borked. I tried to restore it as best as I could remember. But luckily all the labels copied over. @alexpandel  to verify that things look right. 

Apologies again for borking the board.

**Comment by amyashida** [comment]
Reorganized the board and reviewed the wiki content
