### ISSUE TITLE
Intro CSC to Health Tracker Materials / potential templates

### ISSUE THREAD

**Issue by artfulaction** [CMSgov/CMCS-DSG-DSS-Oversight#186]
**Brief description of the task** 

Intro CSC, share materials, suggest templates for other workstreams.

**What steps are needed to make it a reality?**
- [x] Schedule meeting with CSC
- [x] Walk through Health Tracker course site, Rubric, Form, Card view, Github Wiki
- [x] Describe SO Sharepoint wiki, how it relates to above
- [x] Discuss how roll-out plan, material templates, etc could created for certification and service design work.

**Comment by artfulaction** [comment]
Meeting scheduled for the 29th!
