### ISSUE TITLE
Add info identified from leadership interviews to Health Tracker

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#268]
**Brief description of the task** 

We completed interviews with leadership around info that they would like to see/collect via the Health Tracker and synthesized next steps via the [Health Tracker Roadmap](https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1596569564270/d3c81a141ea72d7b6c2db90da408f1b68d3c6ea0). We are going to address the MVP needs for leadership by: 

**What steps are needed to make it a reality?**
- [ ] Associating cost with entries
- [ ] Associating vendor name(s) with entries
- [ ] Updating the roll up view for leadership
- [ ] Onboarding leadership to the roll up view

**Comment by nickarrow** [comment]
Moving to Icebox until we begin Dash-Boarding work.
