### ISSUE TITLE
Define "Coordination Team" OKRs and how 18F can best support that work

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#4]
**Who is the user?**
The coordination team, SOs, states

**What will this help them do?**
Coordinating communications to SOs and states will help ensure a cohesive message, avoid overwhelming users, and increase coordination among the teams. 

**When is it needed?**
This week

**What steps are needed to make it a reality?**
- [x] work with Liz to define OKRs
- [x] outline how 18F can help support the OKRs
- [x] convert next steps into Github issues

**Comment by alexpandel** [comment]
Next steps captured in #57!
