### ISSUE TITLE
Add other relevant info to the wiki

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/CMCS-DSG-DSS-Oversight#6]
**Goal:** anything that _can_ be public, _is_ public (and easily findable) in the wiki.

**Possible things to include:**
- [x] product hypotheses (from [here](https://docs.google.com/document/d/1g09JGJcaX9qwh4-JjH5XJDodogndXag2KK27HwXDppI/edit#heading=h.2qdxb5wcpp79)?)
- [x] user pain points & needs? (from [here](https://docs.google.com/document/d/1g09JGJcaX9qwh4-JjH5XJDodogndXag2KK27HwXDppI/edit#heading=h.2qdxb5wcpp79)?)
- [x] a page with our biweekly ships (a la [this one](https://github.com/18F/eligibility-rules-service/wiki/Weekly-recaps#phase-3---october-1-2018-to-present))?
- [ ] relevant background docs (link to Rosetta Stone & Medicaid IT ecosystem map?)
