### ISSUE TITLE
prep for content strategist onboarding

### ISSUE THREAD

**Issue by alexpandel** [CMSgov/CMCS-DSG-DSS-Oversight#60]
**Who is the user?**
18F content strategist (+ NIck & Liz)

**What will this help them do?**
get oriented to the project quickly so they can hit the ground running

**When is this needed by?**
Ideally by July 1/2

**Definition of done:**
- content strategist feels oriented enough to the project context to be able to lead a workshop to start developing a content governance process by the week of 7/20
- bonus points: content strategist is able to help us prep for introducing idea of content governance on 7/7

**What steps are needed to make it a reality?**
- [x] confirm actual ramp-up timing w/ Elizabeth
- [x] update [project Readme](https://docs.google.com/document/d/1vEK53XkkEWRQPkBjVc12rTOReUko-zFVtDokBDoziGw/edit#) (pull from [kickoff doc](https://docs.google.com/document/d/1537g2Cbi7C2APxURctHsByPkUz3Jpd0RSJb6Xk-ZanA/edit) as appropriate)
- [x] update [onboarding checklist](https://docs.google.com/spreadsheets/d/1h2WaWlyynFMjnrWJ05AI-oRs19wX3lffkxzxLhPenw8/edit#gid=1527234561)
- [x] get user needs/pain points added to [wiki](https://github.com/CMSgov/CMCS-DSG-DSS-Oversight/wiki/User-needs-&-pain-points) (#6)
- [x] get clear on our [biggest content strategy needs](https://docs.google.com/document/d/1vEK53XkkEWRQPkBjVc12rTOReUko-zFVtDokBDoziGw/edit#heading=h.8jfbfcxp84h5) and be prepared to orient our new teammates to those opportunities well
- [x] prep for one-hour internal onboarding meeting on Thurs 7/2 ([agenda here](https://docs.google.com/document/d/1It_TkOM8mdwwvpvkqYVZyf01ERMhHP0Vxn8VtOZ0HwA/edit#heading=h.dnx0b6kkr03l))

**Comment by alexpandel** [comment]
FYI @amyashida, did some work on our [internal Readme](https://docs.google.com/document/d/1vEK53XkkEWRQPkBjVc12rTOReUko-zFVtDokBDoziGw/edit#) today; would love your 👀 on it sometime before like midday Wed to see what you think might still be missing/confusing for a newcomer to the project (I'm thinking we can share this with Princess by EOD on Wed and talk through it together in our meeting on Thurs)

**Comment by alexpandel** [comment]
alright @amyashida, I took a first pass on everything and am reassigning this back to you for your review. Everything is linked in the checklist in the issue description, but a few particular areas where a second opinion would be especially useful:

- does [this](https://docs.google.com/document/d/1It_TkOM8mdwwvpvkqYVZyf01ERMhHP0Vxn8VtOZ0HwA/edit#heading=h.dnx0b6kkr03l) seem like the right stuff to cover in Thursday's meeting? I invited Elizabeth & Glenn as optional; do you think there's anything in particular we need from them?
- I tried to add [a little context](https://docs.google.com/document/d/1vEK53XkkEWRQPkBjVc12rTOReUko-zFVtDokBDoziGw/edit#heading=h.8jfbfcxp84h5) about the different workstreams and the resulting content governance need/opportunity to our Readme, but I feel like it's kinda rambly and unfocused; feel free to clarify or suggest something totally different!
