### ISSUE TITLE
Start getting new 18F team member up to speed

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#63]
**Who is the user?**
18F team, Nick & L

**What will this help them do?**
Make sure everyone is on the same page and ready to drive into content governance

**When is it needed?**
Goal for 7/16

**What steps are needed to make it a reality?**

- [x] Onboarding meeting + Update team charter
- [x] Add Princess to needed meetings
- [x] Add/Scope first focus
