### ISSUE TITLE
Create a roadmap for the Health Tracker

### ISSUE THREAD

**Issue by amyashida** [CMSgov/CMCS-DSG-DSS-Oversight#87]
**Brief description of the task** 

Create a roadmap for the health rubric / visualization to help the blue team and the cross-team better understand the upcoming milestones and how to think about the rubric.

**What steps are needed to make it a reality?**
- [x] 18F + Nick meet to pair on the roadmap
- [x] Nick to add holding tank sextion
- [x] clean up roadmap 
- [ ] Publish roadmap in a place where the group can easily reference it

**Comment by NAretakis** [comment]
Started, but needs a coat of paint. I'll tag in folks when its ready for a look.

**Comment by amyashida** [comment]
@NAretakis could you add the link to the Mural here? I know that it needs to be cleaned up but it would be very helpful to be able to reference it quickly via this card.

**Comment by alexpandel** [comment]
hey @NAretakis, how is this coming? is this somewhere where we can look at/edit it?

**Comment by amyashida** [comment]
Mural sketch of roadmap lives here: https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1596569564270/d3c81a141ea72d7b6c2db90da408f1b68d3c6ea0

**Comment by NAretakis** [comment]
Working on cleanup of the roadmap this week.

**Comment by nickarrow** [comment]
Tracker redesign is on hold until we work through the dash-boarding work. Moving to Icebox.
